"""Update notifications for dealer url

Revision ID: 2bdb6f634eae
Revises: 3fd1d2ef95dc
Create Date: 2024-04-28 19:55:13.665182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdb6f634eae'
down_revision = '3fd1d2ef95dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
