"""Second migration

Revision ID: 4604b261a2e1
Revises: 41c4bdb0ba49
Create Date: 2024-04-09 21:43:39.253289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4604b261a2e1'
down_revision = '41c4bdb0ba49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=80), nullable=False))
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=80), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
