"""Increase password hash

Revision ID: 50579e8f0771
Revises: 4604b261a2e1
Create Date: 2024-04-09 21:45:29.448221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50579e8f0771'
down_revision = '4604b261a2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
