"""empty message

Revision ID: 8743e8f8b2b9
Revises: c5a8b777b5e4
Create Date: 2024-04-21 23:59:09.937803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8743e8f8b2b9'
down_revision = 'c5a8b777b5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idSearch', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('idSearch')

    # ### end Alembic commands ###
